version: '3.8'

services:
  auth-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - beaver-network

networks:
  beaver-network:
    external: true