services:
  auth-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AUTH_GATEWAY_CLIENT_SECRET: ${AUTH_GATEWAY_CLIENT_SECRET}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
    ports:
      - "8000:8000"
    networks:
      - beaver-network

networks:
  beaver-network:
    external: true