server:
  port: 8000

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth-gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: auth-gateway
            client-secret: ${AUTH_GATEWAY_CLIENT_SECRET}
            scope: openid, profile, roles, email
            authorization-grant-type: authorization_code
            redirect-uri: ${KEYCLOAK_REDIRECT_URI}
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}

  session:
    store-type: redis

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1