server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth-gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: auth-gateway
            client-secret: ${AUTH_GATEWAY_CLIENT_SECRET}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/non-production

  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379