server:
  port: 8000

spring:
  application:
    name: auth-gateway
  security:
    oauth2:
      client:
        registration:
          auth-gateway:
            provider: keycloak
            client-id: auth-gateway
            client-secret: rN8uyg1ez6bZdmZq6Qi0UNtWF5bsPXUa
            authorization-grant-type: authorization_code
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://keycloak-service.local:8080/realms/non-production

logging:
  level:
    org.springframework.security.oauth2: INFO
    org.springframework.web.reactive.function.client: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info