server:
  port: 8000

spring:
  application:
    name: auth-gateway
  security:
    oauth2:
      client:
        registration:
          auth-gateway:
            provider: keycloak
            client-id: auth-gateway
            client-secret: ${AUTH_GATEWAY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: preferred_username

logging:
  level:
    org.springframework.web.reactive.function.client: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info